module.exports = {
  HOME_URL: 'http://www.fundamentus.com.br/',
  BASE_URL: 'http://www.fundamentus.com.br/detalhes.php?papel=',
  FIRST_STOCK_ROW: 2,
  FIRST_INDICATOR_COLUMN: 3,
  STOCK_INDICATORS: [
    'P',
    'A',
    'LL',
    'LPA',
    'P/L',
    'VPA',
    'P/VPA',
    'PL',
    'EBIT',
    'ROE',
    'LC',
    'ML',
    'DB',
  ],
  STOCK_INDICATORS_INDEX: [1, 13, 46, 15, 14, 17, 16, 41, 44, 29, 31, 23, 37],
};
